const {chromium}=require('C:/Users/김정진/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs/promises');
(async()=>{
  const out='screenshots';await fs.mkdir(out,{recursive:true});
  const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'});
  const errors=[];
  const desktop=await browser.newPage({viewport:{width:1440,height:1050},deviceScaleFactor:1});
  desktop.on('pageerror',error=>errors.push(error.message));
  const response=await desktop.goto('http://127.0.0.1:8000',{waitUntil:'networkidle'});
  if(!response?.ok())throw new Error('Desktop preview failed to load');
  await desktop.locator('#program-list .program-card').first().waitFor();
  const label=await desktop.locator('#source-status').innerText();
  if(!label.includes('예시'))throw new Error('Demo data state is not clearly labelled');
  await desktop.screenshot({path:`${out}/desktop.png`,fullPage:true});
  await desktop.locator('a[href="#ai"]').first().click();
  await desktop.locator('#question').fill('취업을 준비 중이에요. 직업훈련 정보를 알려 주세요.');
  await desktop.locator('#recommend-button').click();
  await desktop.getByText(/GEMINI_API_KEY/).waitFor();
  await desktop.locator('#ai').scrollIntoViewIfNeeded();
  await desktop.waitForTimeout(500);
  await desktop.screenshot({path:`${out}/ai-key-setup.png`,fullPage:false});
  const mobile=await browser.newPage({viewport:{width:390,height:844},deviceScaleFactor:1,isMobile:true,hasTouch:true});
  mobile.on('pageerror',error=>errors.push(error.message));
  await mobile.goto('http://127.0.0.1:8000',{waitUntil:'networkidle'});
  await mobile.locator('#program-list .program-card').first().waitFor();
  await mobile.screenshot({path:`${out}/mobile.png`,fullPage:true});
  await mobile.locator('.menu-toggle').click();
  const expanded=await mobile.locator('.menu-toggle').getAttribute('aria-expanded');
  if(expanded!=='true')throw new Error('Mobile menu did not open');
  if(errors.length)throw new Error(`Browser errors: ${errors.join('; ')}`);
  console.log(JSON.stringify({desktop:response.status(),sampleCards:await desktop.locator('#program-list .program-card').count(),source:label,mobileMenu:expanded,screenshots:3,pageErrors:errors},null,2));
  await browser.close();
})().catch(error=>{console.error(error);process.exitCode=1;});
